# Generated by Django 3.1.3 on 2020-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_mahasiswa',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('id_kategori', models.IntegerField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/images/')),
            ],
            options={
                'db_table': 'dt_mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Kategori_service',
            fields=[
                ('id_kategori', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
    ]
