# Generated by Django 3.1.3 on 2021-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Barang',
            fields=[
                ('id_kategoribarang', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'kategori_barang',
            },
        ),
    ]
