# Generated by Django 3.1.3 on 2021-01-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210106_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
